application/web/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import DateField, SubmitField, TextAreaField, BooleanField
from flask_wtf.file import FileField, FileRequired

class RangeStats(FlaskForm):
    from_dt = DateField('From Date', format="%m/%d/%Y")
    to_dt = DateField('To Date', format="%m/%d/%Y")
    submit = SubmitField("Get")


class MultipleOnion(FlaskForm):
    urls = TextAreaField("URLs")
    seed_file = FileField("Seed File")
    extract_emails = BooleanField("Extract emails")
    extract_btcaddr = BooleanField("Extract BTC addresses")
    extract_pub_pgp = BooleanField("Extract Pub PGP Key")
    submit = SubmitField("Run Crawler")

application/web/dashboard/__init__.py
from flask import Blueprint

dashboardbp = Blueprint('dashboard', __name__)

from . import views

application/web/dashboard/views.py
import dateutil.parser
from flask import request, redirect, url_for, flash, render_template
from flask_login import login_required
from pymongo import DESCENDING
from .. import client
# from web import q
from .. import run_crawler

from ..scanner.exif_data import detect_exif_metadata

from ..config import *
from ..filters import *
from ..helper import extract_onions
from ..search.forms import SearchForm
from ..stats import onion_stats as oss
from ..paginate import Pagination
from ..scanner import text_subjects, exif_data

from ..queues import detector_q, crawler_q

from werkzeug.utils import secure_filename
from . import dashboardbp
from .forms import *

from bson import ObjectId


@dashboardbp.route('/hs/<id>', methods=["GET"])
def hs_view(id=1):
    search_form = SearchForm()
    try:
        child_data = []
        result = client.crawler.documents.find_one({"_id":ObjectId(id)})
        if result['links']:
            for item in result['links']:
                child_data.append(client.crawler.documents.find_one({"url":item['url']}))
    except:
        print ("ERROR")
    return render_template('dashboard/hs.html',
                           item=result,
                           child_data=child_data,
                           search_form=search_form)


@dashboardbp.route('/hs_directory/', methods=["GET"])
@dashboardbp.route('/hs_directory/<int:page_number>', methods=["GET"])
def hs_directory(page_number=1):
    search_form = SearchForm()
    try:
        all_count = client.crawler.documents.find({'status':200}).count()
        pagination = Pagination(page_number, n_per_page, all_count)
        all = client.crawler.documents.find({ "$and":[{'status':200}, {"in_scope": {"$eq": False}}]}).sort("seen_time", DESCENDING).skip(
            (page_number - 1) * n_per_page).limit(n_per_page)
    except:
        print ("ERROR")
        return render_template('dashboard/hs_directory.html',
                               search_form=search_form,
                               all_count=0)

    return render_template('dashboard/hs_directory.html',
                           results=all,
                           pagination=pagination,
                           search_form=search_form,
                           all_count=all_count)


@dashboardbp.route('/hs/detect_exif/<id>', methods=['GET', 'POST'])
@login_required
def detect_exif_data(id):
    if detect_exif_metadata(id):
        flash("EXIF detection started.")
        return redirect(url_for('dashboard.hs_view', id=id))
    return redirect(url_for('dashboard.hs_view', id=id))


@dashboardbp.route('/hs/detect_subject/<id>', methods=['GET', 'POST'])
@login_required
def detect_subjects(id):
    detector_q.enqueue_call(text_subjects._text_subject, args=(id,), ttl=86400, result_ttl=1)
    flash("Detecting started.", "success")
    return redirect(url_for('dashboard.hs_view', id=id))


@dashboardbp.route('/statistics', methods=['GET', 'POST'])
@login_required
def statistics():
    pass


@dashboardbp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    pass

@dashboardbp.route('/upload_seed', methods=['GET', 'POST'])
@login_required
def upload_seed():
    search_form = SearchForm(request.form)
    multiple_urls_form = MultipleOnion()
    if multiple_urls_form.validate_on_submit():
        seeds = []
        print("FORM")
        if multiple_urls_form.seed_file.data:
            filename = secure_filename(multiple_urls_form.seed_file.data.filename)
            path_to_save = seed_upload_dir + filename
            multiple_urls_form.seed_file.data.save(path_to_save)

            _seed_file = open(path_to_save, 'r')
            seed_file = extract_onions(_seed_file.read())
            _seed_file.close()

            for seed in seed_file:
                seeds.append(seed.strip())

        # print (multiple_urls_form.urls.data)
        # print ("*"*100)
        if multiple_urls_form.urls.data:
            urls = extract_onions(multiple_urls_form.urls.data)
            for url in urls:
                seeds.append(url.strip())

        for seed in seeds:
            print(seed)
            crawler_q.enqueue_call(func=run_crawler, args=(seed,), ttl=86400, result_ttl=1)
            # sleep(0.1) #delay between jobs
            # print (job.result)

        flash('New onions added to crawler queue ', 'success')
        return render_template('dashboard/upload_seed.html', search_form=search_form,
                               multiple_urls_form=multiple_urls_form)

    return render_template('dashboard/upload_seed.html', search_form=search_form,
                           multiple_urls_form=multiple_urls_form)


    print (multiple_urls_form.errors)


@dashboardbp.route('/', methods=['GET', 'POST'])
@login_required
def dashboard():
    search_form = SearchForm(request.form)
    range_stats_form = RangeStats()
    status_count = oss.get_requests_stats_all()
    # print ("*"*1000)
    last_200 = 0
    last_all = 0

    try:
        last_200 = client.crawler.documents.find({"status": 200}).sort("seen_time", DESCENDING).limit(20)
        last_all = client.crawler.documents.find().sort("seen_time", DESCENDING).limit(20)
    except:
        print ("ERROR")

        # return render_template('dashboard.html', search_form=search_form,
        #                        range_stats=range_stats_form, multiple_urls_form=multiple_urls_form)

    # print(list(last_200))
    # print(list(last_all))

    if search_form.validate_on_submit():
        return redirect(url_for('.search', phrase=search_form.phrase.data.lower()))

    if range_stats_form.validate_on_submit():
        if range_stats_form.from_dt.data and range_stats_form.to_dt.data:
            time_series = oss.get_requests_stats(
                dateutil.parser.parse(str(range_stats_form.from_dt.data)),
                dateutil.parser.parse(str(range_stats_form.to_dt.data))
            )
            return render_template('dashboard/dashboard.html', search_form=search_form,
                                   status_count=status_count, range_stats=range_stats_form,
                                   time_series=time_series,multiple_urls_form=multiple_urls_form,
                                   last_200=last_200, last_all=last_all)





    return render_template('dashboard/dashboard.html', search_form=search_form,
                           status_count=status_count, range_stats=range_stats_form,
                            last_200=last_200, last_all=last_all)

application/web/templates/dashboard/dashboard.html
{% extends "base.html" %}
{% block body %}

<!--<script src="{{url_for('static', filename='js/d3.v3.min.js')}}"></script>-->
<script src="{{url_for('static', filename='js/jquery-3.3.1.min.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery-ui.js')}}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/jquery-ui.css')}}" >

    <script>
        $(function() {
            $( ".frmdtpick" ).datepicker();
        });
    </script>

    <script>
        $(function() {
            $( ".todtpick" ).datepicker();
        });
    </script>

<div>



</div>

<div class="col-md-12">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for class, message in messages %}
                <div class="alert alert-{{class}} text-center fixed-top">
                    <i class="glyphicon glyphicon-check" ></i> &nbsp;
                    {{ message }}
                </div>
                {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="col-md-3">
        <h3>
             <i class="glyphicon glyphicon-dashboard"></i>
            &nbsp;Dashboard
        </h3>
    </div>
{% include 'dashboard/nav.html' %}
</div>

<div class="col-md-12 dashboard" style="margin-top: 15px;">
    <h5>
        <i class="glyphicon glyphicon-list"></i>&nbsp;Last LIVE onion page added
    </h5>
    <br/>
    <div>
        {% if last_200 %}
        <table class="table">
            <thead>
                <tr>
                    <td>
                        URL
                    </td>
                    <td>
                        Title
                    </td>
                    <td>
                        Body
                    </td>
                    <td>
                        Parent
                    </td>
                </tr>
            </thead>
            {% for item in last_200 %}
                <tr>
                    <td width="15%">
                        <i class="glyphicon glyphicon-check text-success"></i>&nbsp;
                        {{item.seen_time | datetimeformat}}</td>
                    <td width="25%"><a href="http://{{item.url}}" target="_blank">{{item.url}}</a></td>
                    <td width="25%">{{item.title}}</td>
                    <td width="25%">
                        {% if item.parent %}
                            {{item.parent}}
                        {% else %}
                            <i class="glyphicon glyphicon-check"></i>
                        {% endif %}

                    </td>
                </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
    <hr/>
    <h4>
        <i class="glyphicon glyphicon-list"></i>&nbsp;Last onion page added
    </h4>
    <br/>
    <div>
        {% if last_all %}
        <table class="table">
            {% for item in last_all %}
                <tr>
                    <td>{{item.seen_time | datetimeformat}}</td>
                    <td>{{item.url}}</td>
                    <td>{{item.title}}</td>
                </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>

</div>


{%endblock%}

application/web/templates/dashboard/hs.html
{% extends "base.html" %}
{% block body %}

{% include 'dashboard/nav.html' %}


<div class="container" style="margin-top: 5%;">
    <div>

        <div class="col-lg-6">
                    <a href="{{ url_for('screenshots_path', filename=item.capture_id)}}" target="_blank">
                        <img src="{{ url_for('screenshots_path', filename=item.capture_id)}}" class="col-md-12" style="margin: 10px;">
                    </a>
        </div>
        <div class="col-lg-6">


            <a href="{{url_for('dashboard.detect_subjects', id=item._id)}}" class="btn btn-primary">Detect Subjects</a>
            <a href="{{url_for('dashboard.detect_exif_data', id=item._id)}}">Extract EXIF Metadata</a>
            <a href="{{url_for('dashboard.detect_exif_data', id=item._id)}}">Export report</a>

            <hr/>
            Subjects: <br/>
            {% for item in item.subjects %}
                <a href="" class="btn badge badge-info">{{item}}</a>,
            {% endfor %}

            <br/>
            <hr/>


                        {{item.exif}}

            <br/>
            <hr/>


            <table class="table">
            <tr>
                <td colspan="2"><b>Title</b></td>
                <td colspan="2" width="80%"> {{item.title}}</td>
            </tr>
            <tr>
                <td colspan="2"><b>URL</b></td>
                <td colspan="2" width="80%"> {{item.url}}</td>
            </tr>
            <tr>
                <td>
                    <b>Status:</b>
                </td>
                <td>
                    {{item.status}}
                </td>
                <td>
                    <b>Last seen time:</b>
                </td>
                <td>
                    {{item.seen_time | datetimeformat}}
                </td>
            </tr>
                <tr>
                    <td colspan="2">
                        <b>Parent</b>
                    </td>
                    <td colspan="2">
                        {% if item.parent == None %}
                            <i class="glyphicon glyphicon-star"></i>
                        {% else %}
                            <a class="btn badge badge-info" href="{{url_for('dashboard.hs_view', id=item.parent) }}" target="_blank">{{item.parent}}</a>
                        {% endif %}
                    </td>
                </tr>

            </table>
        </div>

        <div class="col-lg-12">
            <b>Body:</b>
            <br/>
            <textarea style="width: 100%; min-height: 100px;">
                {{item.body}}
            </textarea>
        <hr/>
            <b>HTML</b>
            <br/>
            <textarea style="width: 100%; min-height: 100px;">
                {{item.html}}
            </textarea>
        <hr/>

            {% if item.links: %}
                <h5>Extract Links</h5>
                <table class="table">
                    <tr>
                        <td width="30%">
                            <b>Hidden services</b>
                            <hr/>
                            <ul>
                                {% for select in item.links: %}
                                        {% if select.is_onion == True %}
                                            <li>{{select.url}}
                                                <span class="badge badge-success">ONION</span>
                                            </li>
                                        {% endif %}
                                {% endfor %}
                            </ul>
                        </td>
                        <td width="30%">
                            <b>In-scope links</b>
                            <hr/>
                            <ul>
                                {% for select in item.links: %}
                                        {% if select.in_scope == True %}
                                            <li> {{select.url}}
                                            <span class="badge badge-info">In-scope</span>
                                            </li>
                                        {% endif %}
                                {% endfor %}
                            </ul>
                        </td>
                        <td width="30%">
                            <b>Clearnet links</b>
                            <hr/>
                            <ul>
                                {% for select in item.links: %}
                                        {% if select.is_onion != True and select.in_scope != True %}
                                            <li>
                                                {{select.url}}
                                            </li>
                                        {% endif %}
                                {% endfor %}
                            </ul>
                        </td>
                    </tr>
                </table>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

application/web/templates/dashboard/hs_directory.html
{% extends "base.html" %}
{% block body %}

{% include 'dashboard/nav.html' %}

<style>
    .ds-btn li{ list-style:none; float:left; padding:10px; }
    .ds-btn li a span{padding-left:15px;padding-right:5px;width:100%;display:inline-block; text-align:left;}
    .ds-btn li a span small{width:100%; display:inline-block; text-align:left;}
</style>

<div class="container" style="margin-top: 5%;">
    <div class="col-md-12">

      <h4 class="text-center">
        Total found {{all_count}}
      </h4>
        {% if results:%}
        <ul class="list-unstyled">
            {% for item in results: %}
            <li>
                {% if item.status == 200 %}

                <a href="{{ url_for('screenshots_path', filename=item.capture_id)}}" target="_blank">
                    <img src="{{ url_for('screenshots_path', filename=item.capture_id)}}" class="pull-left img-thumbnail col-md-2" style="margin: 10px;">
                </a>

                {% endif %}

                {% if item.title %}
                <a target="_blank" href="http://{{item.url}}">
                    <span class="highlight">{{item.title}}</span> &nbsp;

                </a>
                <a style="display: inline-block;" class="btn badge badge-danger" href="{{url_for('dashboard.hs_view', id=item._id) }}" >VIEW</a>

                <br/>
                {% endif %}
                <a target="_blank" href="http://{{item.url}}">{{item.url}}</a>
                <span class="badge badge-primary">{{item.seen_time | datetimeformat}}</span>
                <span style="display: inline-block;" class="badge">{{item.status}}</span>
                {% if item.body %}
                <p style="word-wrap: break-word;">
                    {{item.body | limitbody(256)}}
                </p>
                {% endif %}
                {% if item.links | length %}
                    <span class="badge badge-info">{{item.links | length}} Included links</span>
                {% endif %}
                <div class="clearfix"></div>
                <hr>
            </li>
            {% endfor %}
        </ul>

  <ul class=pagination>
  {%- for page in pagination.iter_pages() %}
    {% if page %}
      {% if page != pagination.page %}
        {% if is_all %}
        <li><a href="{{url_for('search.directory_all',page_number=page)}}">{{ page }}</a></li>
        {%else%}
        <li><a href="{{url_for('search.directory',page_number=page)}}">{{ page }}</a></li>
        {% endif %}
      {% else %}
        {% if is_all %}
        <li><a href="{{url_for('search.directory_all',page_number=page)}}"><strong>{{ page }}</strong></a></li>
        {%else%}
        <li><a href="{{url_for('search.directory',page_number=page)}}"><strong>{{ page }}</strong></a></li>
        {% endif %}
      {% endif %}
    {% else %}

    {% endif %}
  {%- endfor %}
  {% if pagination.has_next %}
        {% if is_all %}
          <li><a href="{{url_for('search.directory_all', page_number=pagination.page + 1)}}">Next &raquo;</a></li>
        {% else %}
          <li><a href="{{url_for('search.directory', page_number=pagination.page + 1)}}">Next &raquo;</a></li>
        {% endif %}
  {% endif %}
  </ul>

  </div>

    {% endif %}
</div>

{% endblock %}

application/web/templates/dashboard/nav.html
<div class="btn-group" role="group" aria-label="Admin Controllers">
  <a href="{{url_for('dashboard.dashboard')}}" class="btn btn-secondary">
      <i class="glyphicon glyphicon-adjust"></i>
      Dashboard</a>
  <a href="{{url_for('dashboard.upload_seed')}}" class="btn btn-secondary">
          <i class="glyphicon glyphicon-upload"></i>
          Upload Seed
  </a>
  <a href="{{url_for('scanner.scanner_overview')}}" class="btn btn-secondary">
      <i class="glyphicon glyphicon-screenshot"></i>
      Scanner
  </a>
  <a href="{{url_for('dashboard.hs_directory')}}" class="btn btn-secondary">
      <i class="glyphicon glyphicon-ok-circle"></i>
      Hidden Service Directory</a>
  <a href="{{url_for('dashboard.statistics')}}" class="btn btn-secondary">
      <i class="glyphicon glyphicon-stats"></i>
      Statistics</a>
  <a href="{{url_for('dashboard.settings')}}" class="btn btn-secondary">
      <i class="glyphicon glyphicon-list-alt"></i>
      Settings</a>

</div>

application/web/templates/dashboard/upload_seed.html
{% extends "base.html" %}
{% block body %}

<!--<script src="{{url_for('static', filename='js/d3.v3.min.js')}}"></script>-->
<script src="{{url_for('static', filename='js/jquery-3.3.1.min.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery-ui.js')}}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/jquery-ui.css')}}" >


<div class="col-md-12">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for class, message in messages %}
                <div class="alert alert-{{class}} text-center fixed-top">
                    <i class="glyphicon glyphicon-check" ></i> &nbsp;
                    {{ message }}
                </div>
                {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="col-md-3">
        <h3>
             <i class="glyphicon glyphicon-dashboard"></i>
            &nbsp;Dashboard
        </h3>
    </div>
{% include 'dashboard/nav.html' %}
</div>

<div class="col-md-12 dashboard" style="margin-top: 15px;">
    <h4>
        <i class="glyphicon glyphicon-list"></i>Upload a seed
    </h4>
    <hr/>
    <div class="col-md-12">
        <form method="POST" enctype="multipart/form-data" action="{{url_for('dashboard.upload_seed')}}">
            <table class="table table-bordered">
              <tr>
                <th>Upload your seed list or paste the list in the text area field.</th>
                <td>
                        {{multiple_urls_form.seed_file(class="form-control", style="height: auto;")}}
                </td>
              </tr>
              <tr>
                <th rowspan="2">
                        {{multiple_urls_form.urls(class="form-control", style="height: 140px;")}}
                </th>
                <td class="text-center" style="max-width: 300px;">
                    <table class="table">
                        <tr>
                            <td><b>EMAILS</b></td><td>{{multiple_urls_form.extract_emails(style="display:inline;")}}</td>
                            <td><b>BITCOIN ADDRESSES</b></td><td>{{multiple_urls_form.extract_btcaddr(style="display:inline;") }}</td>
                        </tr>
                        <tr>
                            <td>
                                <b>PUBLIC PGP</b>
                            </td>
                            <td>
                                {{multiple_urls_form.extract_pub_pgp(style="display:inline;", disabled="disabled") }}
                            </td>
                      <td>
                        <b>EXIF Check</b>

                            </td>
                            <td>
                                {{multiple_urls_form.extract_pub_pgp(style="display:inline;", disabled="disabled") }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <b>PRIVATE PGP</b>
                            </td>
                            <td>
                                {{multiple_urls_form.extract_pub_pgp(style="display:inline;", disabled="disabled") }}
                            </td>
                        </tr>
                        <tr>

                        </tr>
                    </table>
                </td>
              </tr>
              <tr>
                <td class="text-center">
                        {{multiple_urls_form.submit(class="btn btn-success")}}

                </td>
              </tr>
            </table>
            {{multiple_urls_form.csrf_token() }}
        </form>

    </div>
</div>

{%endblock%}